### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [mjmgooch/food-hygiene-ratings#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by mjmgooch** [comment]
Go for it @geopic I'm all for making this more usable. Feel free to submit a PR 👍

**Comment by geopic** [comment]
Excellent, I'll get started on it now.

**Comment by threesquared** [comment]
This doesn't seem to have made it into a NPM release yet. Can this get released at some point thanks.
